import "dotenv/config";
const {
  HOST_NAME,
  PORT,
  MONGO_URI,
  AUTH_USER_EMAIL,
  AUTH_PASSWORD,
  EXPIRE_IN_FIFTEEN_MINUTES,
  EXPIRE_IN_DAY,
  JWT_SECRET,
  JWT_EXPIRY,
  PASSWORD_SECRET,
} = process.env;

export {
  HOST_NAME,
  PORT,
  MONGO_URI,
  AUTH_USER_EMAIL,
  AUTH_PASSWORD,
  EXPIRE_IN_FIFTEEN_MINUTES,
  EXPIRE_IN_DAY,
  JWT_SECRET,
  JWT_EXPIRY,
  PASSWORD_SECRET,
};
